name = "noraebang-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
# Non-secret env vars go here (or use `wrangler secret put` for secrets)

[[kv_namespaces]]
binding = "KARAOKE_CACHE"
id = "6346956c92ad4d598b52962436ac1bda"
preview_id = "c2b6f8e30bd84d59b29d525bb76f39e9"

[triggers]
crons = ["0 3 * * *"]
